version: '3.8'

services:
  app:
    build: .
    container_name: financello-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/financello_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=adminadmin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: financello_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/data-test.sql:/docker-entrypoint-initdb.d/data-test.sql

volumes:
  postgres-data: